const abrasf204 = {
    gerarNfseEnvio: "GerarNfseEnvio",
    consultarLoteRpsEnvio: "ConsultarLoteRpsEnvio",
    enviarLoteRpsEnvio: "EnviarLoteRpsEnvio",
    cancelarNfseEnvio: "CancelarNfseEnvio",
    consultarNfseRpsEnvio: "ConsultarNfseRpsEnvio",
    loteRps: "LoteRps",
    numeroLote: "NumeroLote",
    prestador: "Prestador",
    cpfCnpj: "CpfCnpj",
    infPedidoCancelamento: "InfPedidoCancelamento",
    cpf: "Cpf",
    cnpj: "Cnpj",
    inscricaoMunicipal: "InscricaoMunicipal",
    quantidadeRps: "QuantidadeRps",
    listaRps: "ListaRps",
    rps: "Rps",
    infDeclaracaoPrestacaoServico: "InfDeclaracaoPrestacaoServico",
    rps: "Rps",
    //infRpsFinal: "InfRps",
    
    identificacaoRps: "IdentificacaoRps",
    numero: "Numero",
    serie: "Serie",
    tipo: "Tipo",
    // dataEmissaoRps: "DataEmissaoRps",
    dataEmissao: "DataEmissao",
    //naturezaOperacao: "NaturezaOperacao",
    status: "Status",

    // dataEmissao: "DataEmissao", // referente a dedução
    competencia: "Competencia",

    // rpsSubstituido: "RpsSubstituido",
    // numero: "Numero",
    // serie: "Serie",
    // tipo: "Tipo",
    servico: "Servico",
    valores: "Valores",
    valorServicos: "ValorServicos",
    valorDeducoes: "ValorDeducoes",
    valorPis: "ValorPis",
    valorCofins: "ValorCofins",
    valorInss: "ValorInss",
    valorIr: "ValorIr",
    valorCsll: "ValorCsll",
    outrasRetencoes: "OutrasRetencoes",
    valTotTributos: "ValTotTributos",
    valorIss: "ValorIss",
    aliquota: "Aliquota",
    //valorLiquidoNfse: "ValorLiquidoNfse",
    descontoIncondicionado: "DescontoIncondicionado",
    descontoCondicionado: "DescontoCondicionado",

    // valorIssRetido: "ValorIssRetido",
    issRetido: "IssRetido",
    responsavelRetencao: "ResponsavelRetencao",
    //baseCalculo: "BaseCalculo",
    itemListaServico: "ItemListaServico",
    codigoCnae: "CodigoCnae",
    //codigoTributacaoMunicipio: "CodigoTributacaoMunicipio",
    discriminacao: "Discriminacao",
    codigoMunicipio: "CodigoMunicipio",
    codigoPais: "CodigoPais",
    exigibilidadeISS: "ExigibilidadeISS",
    municipioIncidencia: "MunicipioIncidencia",

    prestador: "Prestador",
    cpfCnpj: "CpfCnpj",
    cpf: "Cpf",
    cnpj: "Cnpj",
    inscricaoMunicipal: "InscricaoMunicipal",

    tomadorServico: "TomadorServico",
    identificacaoTomador: "IdentificacaoTomador",
    cpfCnpj: "CpfCnpj",
    cpf: "Cpf",
    cnpj: "Cnpj",
    razaoSocial: "RazaoSocial",
    endereco: "Endereco",
    numero: "Numero",
    complemento: "Complemento",
    bairro: "Bairro",
    codigoMunicipio: "CodigoMunicipio",
    uf: "Uf",
    cep: "Cep",
    contato: "Contato",
    telefone: "Telefone",
    email: "Email",

    regimeEspecialTributacao: "RegimeEspecialTributacao",
    optanteSimplesNacional: "OptanteSimplesNacional",
    // incentivadorCultural: "IncentivadorCultural",
    incentivoFiscal: "IncentivoFiscal",
    informacoesComplementares: "InformacoesComplementares",
    // intermediarioServico: "IntermediarioServico",
    // razaoSocial: "RazaoSocial",
    // cnpj: "Cnpj",
    // inscricaoMunicipal: "InscricaoMunicipal",
    // contrucaoCivil: "ContrucaoCivil",
    // codigoObra: "CodigoObra",
    // art: "Art",
    protocolo: "Protocolo",
    // infPedidoCancelamento: "InfPedidoCancelamento",
    pedido: "Pedido",
    identificacaoNfse: "IdentificacaoNfse",
    codigoCancelamento: "CodigoCancelamento"
};

module.exports = {
    abrasf204
}